using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace SmartContract.Infrastructure.Resources.PDFAPI
{
    public class FM_CONTRACT_T05_Request
    {
        public string REQUEST_ID { get; set; } = "{REQUEST_ID}";
        public string F02 { get; set; } = "{F02}";
        public string F01 { get; set; } = "{F01}";
        public string F03 { get; set; } = "{F03}";
        public string F04 { get; set; } = "{F04}";
        public string F05 { get; set; } = "{F05}";
        public string F06 { get; set; } = "{F06}";
        public string F07 { get; set; } = "{F07}";
        public string F08 { get; set; } = "{F08}";
        public string F09 { get; set; } = "{F09}";
        public string F10 { get; set; } = "{F10}";
        public string F11 { get; set; } = "{F11}";
        public string F12 { get; set; } = "{F12}";
        public string F13 { get; set; } = "{F13}";
        public string F14 { get; set; } = "{F14}";
        public string F15 { get; set; } = "{F15}";
        public string HEAD { get; set; } = "{HEAD}";
        public string F16 { get; set; } = "{F16}";
        public string F17 { get; set; } = "{F17}";
        public string F18 { get; set; } = "{F18}";
        public string F19 { get; set; } = "{F19}";
        public string F20 { get; set; } = "{F20}";
        public string F21 { get; set; } = "{F21}";
        public string F22 { get; set; } = "{F22}";
        public string F23 { get; set; } = "{F23}";
        public string F24 { get; set; } = "{F24}";
        public string F25 { get; set; } = "{F25}";
        public string F26 { get; set; } = "{F26}";
        public string F27 { get; set; } = "{F27}";
        public string F28 { get; set; } = "{F28}";
        public string F29 { get; set; } = "{F29}";
        public string F30 { get; set; } = "{F30}";
        public string F31 { get; set; } = "{F31}";
        public string F32 { get; set; } = "{F32}";
        public string F33 { get; set; } = "{F33}";
        public string F34 { get; set; } = "{F34}";
        public string F35 { get; set; } = "{F35}";
        public string F36 { get; set; } = "{F36}";
        public string F37 { get; set; } = "{F37}";
        public string F38 { get; set; } = "{F38}";
        public string F39 { get; set; } = "{F39}";
        public string F40 { get; set; } = "{F40}";
        public string F41 { get; set; } = "{F41}";
        public string F42 { get; set; } = "{F42}";
        public string F43 { get; set; } = "{F43}";
        public string F44 { get; set; } = "{F44}";
        public string F45 { get; set; } = "{F45}";
        public string F46 { get; set; } = "{F46}";
        public string F47 { get; set; } = "{F47}";
        public string F48 { get; set; } = "{F48}";
        public string F49 { get; set; } = "{F49}";
        public string F50 { get; set; } = "{F50}";
        public string F51 { get; set; } = "{F51}";
        public string F52 { get; set; } = "{F52}";
        public string F53 { get; set; } = "{F53}";
        public string F54 { get; set; } = "{F54}";
        public string F55 { get; set; } = "{F55}";
        public string F56 { get; set; } = "{F56}";
        public string F57 { get; set; } = "{F57}";
        public string F58 { get; set; } = "{F58}";
        public string F59 { get; set; } = "{F59}";
        public string F60 { get; set; } = "{F60}";
        public string ID { get; set; } = "{ID}";
        public string F61 { get; set; } = "{F61}";
        public string F62 { get; set; } = "{F62}";
        public string F63 { get; set; } = "{F63}";
        public string F20_1 { get; set; } = "{F20_1}";
        public string F28_1 { get; set; } = "{F28_1}";
        public string F64 { get; set; } = "{F64}";
        public string F65 { get; set; } = "{F65}";
        public string F66 { get; set; } = "{F66}";
        public string F67 { get; set; } = "{F67}";
        public string F68 { get; set; } = "{F68}";
        public string F69 { get; set; } = "{F69}";
        public string F70 { get; set; } = "{F70}";
        public string F71 { get; set; } = "{F71}";
        public string F72 { get; set; } = "{F72}";
        public string F73 { get; set; } = "{F73}";
        public string F75 { get; set; } = "{F75}";
        public string F76 { get; set; } = "{F76}";
        public string F77 { get; set; } = "{F77}";
        public string F78 { get; set; } = "{F78}";
        public string F79 { get; set; } = "{F79}";
        public string F80 { get; set; } = "{F80}";
        public string F74 { get; set; } = "{F74}";
        public string F81 { get; set; } = "{F81}";
        public string F82 { get; set; } = "{F82}";
        public string F83 { get; set; } = "{F83}";
        public string F84 { get; set; } = "{F84}";
        public string F85 { get; set; } = "{F85}";
        public string CB1 { get; set; } = "{CB1}";
        public string CB2 { get; set; } = "{CB2}";
        public string CB3 { get; set; } = "{CB3}";
        public string CB4 { get; set; } = "{CB4}";
        public string CB5 { get; set; } = "{CB5}";
        public string CB6 { get; set; } = "{CB6}";
        public string CB7 { get; set; } = "{CB7}";
        public string CB8 { get; set; } = "{CB8}";
        public string CB9 { get; set; } = "{CB9}";
        public string CB10 { get; set; } = "{CB10}";
        public string CB11 { get; set; } = "{CB11}";
        public string CB12 { get; set; } = "{CB12}";
        public string CB13 { get; set; } = "{CB13}";
        public string CB14 { get; set; } = "{CB14}";
        public string CB15 { get; set; } = "{CB15}";
        public string CB16 { get; set; } = "{CB16}";
        public string CB17 { get; set; } = "{CB17}";
        public string CB18 { get; set; } = "{CB18}";
        public string TYPE { get; set; } = "{TYPE}";
        public string FSignature01 { get; set; } = "{FSignature01}";
        public string FSignature02 { get; set; } = "{FSignature02}";
        public string FSignature03 { get; set; } = "{FSignature03}";
        public string FSignature04 { get; set; } = "{FSignature04}";
        public string FSignaturefootnote01 { get; set; } = "{FSignaturefootnote01}";
        public string FSignaturefootnote02 { get; set; } = "{FSignaturefootnote02}";
    }
}
