//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ServiceIAMAuthentication
{
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ws.iam.nhso.go.th/", ConfigurationName="ServiceIAMAuthentication.Authentication")]
    public interface Authentication
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(domainInfo[]))]
        System.Threading.Tasks.Task<ServiceIAMAuthentication.authenAndUserInfoResponse> authenAndUserInfoAsync(ServiceIAMAuthentication.authenAndUserInfo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(domainInfo[]))]
        System.Threading.Tasks.Task<ServiceIAMAuthentication.authenResponse> authenAsync(ServiceIAMAuthentication.authen request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(domainInfo[]))]
        System.Threading.Tasks.Task<ServiceIAMAuthentication.getDomainResponse> getDomainAsync(ServiceIAMAuthentication.getDomain request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(domainInfo[]))]
        System.Threading.Tasks.Task<ServiceIAMAuthentication.echoResponse> echoAsync(ServiceIAMAuthentication.echo request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(domainInfo[]))]
        System.Threading.Tasks.Task<ServiceIAMAuthentication.checkUserResponse> checkUserAsync(ServiceIAMAuthentication.checkUser request);
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(domainInfo[]))]
        System.Threading.Tasks.Task<ServiceIAMAuthentication.getActiveDomainResponse> getActiveDomainAsync(ServiceIAMAuthentication.getActiveDomain request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.iam.nhso.go.th/")]
    public partial class authenWSRequest
    {
        
        private string domainNameField;
        
        private string userNameField;
        
        private string passwordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string domainName
        {
            get
            {
                return this.domainNameField;
            }
            set
            {
                this.domainNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string password
        {
            get
            {
                return this.passwordField;
            }
            set
            {
                this.passwordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.iam.nhso.go.th/")]
    public partial class domainInfo
    {
        
        private bool activeField;
        
        private string domainField;
        
        private string domainNameField;
        
        private int seqField;
        
        private string zoneCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string domain
        {
            get
            {
                return this.domainField;
            }
            set
            {
                this.domainField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string domainName
        {
            get
            {
                return this.domainNameField;
            }
            set
            {
                this.domainNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int seq
        {
            get
            {
                return this.seqField;
            }
            set
            {
                this.seqField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string zoneCode
        {
            get
            {
                return this.zoneCodeField;
            }
            set
            {
                this.zoneCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.iam.nhso.go.th/")]
    public partial class domainResponse
    {
        
        private string codeField;
        
        private domainInfo[] domainsField;
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        [System.Xml.Serialization.XmlArrayItemAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=false)]
        public domainInfo[] domains
        {
            get
            {
                return this.domainsField;
            }
            set
            {
                this.domainsField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.iam.nhso.go.th/")]
    public partial class userInfo
    {
        
        private string departmentField;
        
        private string descriptionField;
        
        private string displayNameField;
        
        private string distinguishedNameField;
        
        private string domainNameField;
        
        private string emailField;
        
        private string employeeIDField;
        
        private string firstNameField;
        
        private string infoField;
        
        private string lastNameField;
        
        private string signImageField;
        
        private string userNameField;
        
        private string zoneCodeField;
        
        private string zoneNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string department
        {
            get
            {
                return this.departmentField;
            }
            set
            {
                this.departmentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string displayName
        {
            get
            {
                return this.displayNameField;
            }
            set
            {
                this.displayNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string distinguishedName
        {
            get
            {
                return this.distinguishedNameField;
            }
            set
            {
                this.distinguishedNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string domainName
        {
            get
            {
                return this.domainNameField;
            }
            set
            {
                this.domainNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string email
        {
            get
            {
                return this.emailField;
            }
            set
            {
                this.emailField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string employeeID
        {
            get
            {
                return this.employeeIDField;
            }
            set
            {
                this.employeeIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string firstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string info
        {
            get
            {
                return this.infoField;
            }
            set
            {
                this.infoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string lastName
        {
            get
            {
                return this.lastNameField;
            }
            set
            {
                this.lastNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string signImage
        {
            get
            {
                return this.signImageField;
            }
            set
            {
                this.signImageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=11)]
        public string userName
        {
            get
            {
                return this.userNameField;
            }
            set
            {
                this.userNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=12)]
        public string zoneCode
        {
            get
            {
                return this.zoneCodeField;
            }
            set
            {
                this.zoneCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=13)]
        public string zoneName
        {
            get
            {
                return this.zoneNameField;
            }
            set
            {
                this.zoneNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ws.iam.nhso.go.th/")]
    public partial class authenWSResponse
    {
        
        private string codeField;
        
        private string messageField;
        
        private userInfo userInfoField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string message
        {
            get
            {
                return this.messageField;
            }
            set
            {
                this.messageField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public userInfo userInfo
        {
            get
            {
                return this.userInfoField;
            }
            set
            {
                this.userInfoField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authenAndUserInfo", WrapperNamespace="http://ws.iam.nhso.go.th/", IsWrapped=true)]
    public partial class authenAndUserInfo
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.iam.nhso.go.th/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIAMAuthentication.authenWSRequest arg0;
        
        public authenAndUserInfo()
        {
        }
        
        public authenAndUserInfo(ServiceIAMAuthentication.authenWSRequest arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authenAndUserInfoResponse", WrapperNamespace="http://ws.iam.nhso.go.th/", IsWrapped=true)]
    public partial class authenAndUserInfoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.iam.nhso.go.th/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIAMAuthentication.authenWSResponse @return;
        
        public authenAndUserInfoResponse()
        {
        }
        
        public authenAndUserInfoResponse(ServiceIAMAuthentication.authenWSResponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authen", WrapperNamespace="http://ws.iam.nhso.go.th/", IsWrapped=true)]
    public partial class authen
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.iam.nhso.go.th/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIAMAuthentication.authenWSRequest authenWSRequest;
        
        public authen()
        {
        }
        
        public authen(ServiceIAMAuthentication.authenWSRequest authenWSRequest)
        {
            this.authenWSRequest = authenWSRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="authenResponse", WrapperNamespace="http://ws.iam.nhso.go.th/", IsWrapped=true)]
    public partial class authenResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.iam.nhso.go.th/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIAMAuthentication.authenWSResponse @return;
        
        public authenResponse()
        {
        }
        
        public authenResponse(ServiceIAMAuthentication.authenWSResponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDomain", WrapperNamespace="http://ws.iam.nhso.go.th/", IsWrapped=true)]
    public partial class getDomain
    {
        
        public getDomain()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getDomainResponse", WrapperNamespace="http://ws.iam.nhso.go.th/", IsWrapped=true)]
    public partial class getDomainResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.iam.nhso.go.th/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIAMAuthentication.domainResponse @return;
        
        public getDomainResponse()
        {
        }
        
        public getDomainResponse(ServiceIAMAuthentication.domainResponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echo", WrapperNamespace="http://ws.iam.nhso.go.th/", IsWrapped=true)]
    public partial class echo
    {
        
        public echo()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="echoResponse", WrapperNamespace="http://ws.iam.nhso.go.th/", IsWrapped=true)]
    public partial class echoResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.iam.nhso.go.th/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public echoResponse()
        {
        }
        
        public echoResponse(string @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkUser", WrapperNamespace="http://ws.iam.nhso.go.th/", IsWrapped=true)]
    public partial class checkUser
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.iam.nhso.go.th/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIAMAuthentication.authenWSRequest arg0;
        
        public checkUser()
        {
        }
        
        public checkUser(ServiceIAMAuthentication.authenWSRequest arg0)
        {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="checkUserResponse", WrapperNamespace="http://ws.iam.nhso.go.th/", IsWrapped=true)]
    public partial class checkUserResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.iam.nhso.go.th/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIAMAuthentication.authenWSResponse @return;
        
        public checkUserResponse()
        {
        }
        
        public checkUserResponse(ServiceIAMAuthentication.authenWSResponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getActiveDomain", WrapperNamespace="http://ws.iam.nhso.go.th/", IsWrapped=true)]
    public partial class getActiveDomain
    {
        
        public getActiveDomain()
        {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getActiveDomainResponse", WrapperNamespace="http://ws.iam.nhso.go.th/", IsWrapped=true)]
    public partial class getActiveDomainResponse
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ws.iam.nhso.go.th/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public ServiceIAMAuthentication.domainResponse @return;
        
        public getActiveDomainResponse()
        {
        }
        
        public getActiveDomainResponse(ServiceIAMAuthentication.domainResponse @return)
        {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public interface AuthenticationChannel : ServiceIAMAuthentication.Authentication, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.3-preview3.21351.2")]
    public partial class AuthenticationClient : System.ServiceModel.ClientBase<ServiceIAMAuthentication.Authentication>, ServiceIAMAuthentication.Authentication
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public AuthenticationClient() : 
                base(AuthenticationClient.GetDefaultBinding(), AuthenticationClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.AuthenticationImplPort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationClient(EndpointConfiguration endpointConfiguration) : 
                base(AuthenticationClient.GetBindingForEndpoint(endpointConfiguration), AuthenticationClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(AuthenticationClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(AuthenticationClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public AuthenticationClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceIAMAuthentication.authenAndUserInfoResponse> ServiceIAMAuthentication.Authentication.authenAndUserInfoAsync(ServiceIAMAuthentication.authenAndUserInfo request)
        {
            return base.Channel.authenAndUserInfoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceIAMAuthentication.authenAndUserInfoResponse> authenAndUserInfoAsync(ServiceIAMAuthentication.authenWSRequest arg0)
        {
            ServiceIAMAuthentication.authenAndUserInfo inValue = new ServiceIAMAuthentication.authenAndUserInfo();
            inValue.arg0 = arg0;
            return ((ServiceIAMAuthentication.Authentication)(this)).authenAndUserInfoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceIAMAuthentication.authenResponse> ServiceIAMAuthentication.Authentication.authenAsync(ServiceIAMAuthentication.authen request)
        {
            return base.Channel.authenAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceIAMAuthentication.authenResponse> authenAsync(ServiceIAMAuthentication.authenWSRequest authenWSRequest)
        {
            ServiceIAMAuthentication.authen inValue = new ServiceIAMAuthentication.authen();
            inValue.authenWSRequest = authenWSRequest;
            return ((ServiceIAMAuthentication.Authentication)(this)).authenAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceIAMAuthentication.getDomainResponse> ServiceIAMAuthentication.Authentication.getDomainAsync(ServiceIAMAuthentication.getDomain request)
        {
            return base.Channel.getDomainAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceIAMAuthentication.getDomainResponse> getDomainAsync()
        {
            ServiceIAMAuthentication.getDomain inValue = new ServiceIAMAuthentication.getDomain();
            return ((ServiceIAMAuthentication.Authentication)(this)).getDomainAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceIAMAuthentication.echoResponse> ServiceIAMAuthentication.Authentication.echoAsync(ServiceIAMAuthentication.echo request)
        {
            return base.Channel.echoAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceIAMAuthentication.echoResponse> echoAsync()
        {
            ServiceIAMAuthentication.echo inValue = new ServiceIAMAuthentication.echo();
            return ((ServiceIAMAuthentication.Authentication)(this)).echoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceIAMAuthentication.checkUserResponse> ServiceIAMAuthentication.Authentication.checkUserAsync(ServiceIAMAuthentication.checkUser request)
        {
            return base.Channel.checkUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceIAMAuthentication.checkUserResponse> checkUserAsync(ServiceIAMAuthentication.authenWSRequest arg0)
        {
            ServiceIAMAuthentication.checkUser inValue = new ServiceIAMAuthentication.checkUser();
            inValue.arg0 = arg0;
            return ((ServiceIAMAuthentication.Authentication)(this)).checkUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ServiceIAMAuthentication.getActiveDomainResponse> ServiceIAMAuthentication.Authentication.getActiveDomainAsync(ServiceIAMAuthentication.getActiveDomain request)
        {
            return base.Channel.getActiveDomainAsync(request);
        }
        
        public System.Threading.Tasks.Task<ServiceIAMAuthentication.getActiveDomainResponse> getActiveDomainAsync()
        {
            ServiceIAMAuthentication.getActiveDomain inValue = new ServiceIAMAuthentication.getActiveDomain();
            return ((ServiceIAMAuthentication.Authentication)(this)).getActiveDomainAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthenticationImplPort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.AuthenticationImplPort))
            {
                return new System.ServiceModel.EndpointAddress("http://192.168.202.84:28080/iamws/services/Authentication");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return AuthenticationClient.GetBindingForEndpoint(EndpointConfiguration.AuthenticationImplPort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return AuthenticationClient.GetEndpointAddress(EndpointConfiguration.AuthenticationImplPort);
        }
        
        public enum EndpointConfiguration
        {
            
            AuthenticationImplPort,
        }
    }
}
